# Generated by Django 5.2.7 on 2025-11-14 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(help_text='Ex: Caixa 1, Entrada, Setor A', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('porta', models.IntegerField(default=554)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('senha', models.CharField(blank=True, max_length=100)),
                ('url_stream', models.CharField(help_text='URL completa do stream RTSP/HTTP', max_length=500)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('MANUTENCAO', 'Em Manutenção'), ('ERRO', 'Com Erro')], default='ATIVA', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('resolucao', models.CharField(default='1920x1080', max_length=20)),
                ('fps', models.IntegerField(default=30, help_text='Frames por segundo')),
                ('gravar_continuamente', models.BooleanField(default=False)),
                ('tempo_retencao_dias', models.IntegerField(default=30, help_text='Dias para manter gravações')),
                ('ultima_conexao', models.DateTimeField(blank=True, null=True)),
                ('ultima_deteccao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem_referencia', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CameraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERRO_CONEXAO', 'Erro de Conexão'), ('ERRO_AUTENTICACAO', 'Erro de Autenticação'), ('BAIXA_QUALIDADE', 'Baixa Qualidade')], max_length=30)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('qualidade_sinal', models.IntegerField(blank=True, help_text='0-100%', null=True)),
                ('latencia_ms', models.IntegerField(blank=True, help_text='Latência em milissegundos', null=True)),
                ('fps_atual', models.IntegerField(blank=True, null=True)),
                ('codigo_erro', models.CharField(blank=True, max_length=50)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('duracao_minutos', models.IntegerField(blank=True, help_text='Quanto tempo ficou neste status', null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='verifik.camera')),
            ],
            options={
                'verbose_name': 'Status de Câmera',
                'verbose_name_plural': 'Histórico de Status das Câmeras',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='DeteccaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_deteccao', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_deteccao', models.CharField(choices=[('VIDEO', 'Vídeo/Visão Computacional'), ('OCR', 'OCR/Leitura de Texto'), ('MANUAL', 'Identificação Manual')], max_length=20)),
                ('confianca', models.FloatField(help_text='Nível de confiança da IA (0-100%)')),
                ('marca_detectada', models.CharField(blank=True, max_length=100)),
                ('tipo_detectado', models.CharField(blank=True, max_length=100)),
                ('codigo_detectado', models.CharField(blank=True, max_length=50)),
                ('imagem_capturada', models.ImageField(blank=True, null=True, upload_to='deteccoes/')),
                ('dados_raw', models.JSONField(blank=True, help_text='Dados brutos da IA', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.camera')),
                ('produto_identificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.produto')),
            ],
            options={
                'verbose_name': 'Detecção de Produto',
                'verbose_name_plural': 'Detecções de Produtos',
                'ordering': ['-data_hora_deteccao'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_incidente', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('PRODUTO_NAO_REGISTRADO', 'Produto Entregue Não Registrado'), ('QUANTIDADE_DIVERGENTE', 'Quantidade Divergente'), ('PRODUTO_DIFERENTE', 'Produto Diferente do Registrado'), ('OUTRO', 'Outro')], max_length=30)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_INVESTIGACAO', 'Em Investigação'), ('CONFIRMADO', 'Confirmado'), ('FALSO_POSITIVO', 'Falso Positivo'), ('RESOLVIDO', 'Resolvido')], default='PENDENTE', max_length=20)),
                ('data_hora_ocorrencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('observacoes_analise', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.camera')),
                ('deteccao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.deteccaoproduto')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.funcionario')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-data_hora_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('IMAGEM', 'Imagem'), ('AUDIO', 'Áudio'), ('DOCUMENTO', 'Documento'), ('LOG', 'Log do Sistema')], max_length=20)),
                ('arquivo', models.FileField(upload_to='evidencias/')),
                ('descricao', models.TextField(blank=True)),
                ('duracao_segundos', models.IntegerField(blank=True, help_text='Para vídeos/áudios', null=True)),
                ('timestamp_relevante', models.CharField(blank=True, help_text='Momento relevante no vídeo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='verifik.incidente')),
            ],
            options={
                'verbose_name': 'Evidência de Incidente',
                'verbose_name_plural': 'Evidências de Incidentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCIDENTE', 'Incidente Detectado'), ('CAMERA_INATIVA', 'Câmera Inativa'), ('SISTEMA', 'Alerta do Sistema'), ('RELATORIO', 'Relatório Agendado')], max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('PAINEL', 'Painel Web'), ('SMS', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('FALHOU', 'Falhou'), ('LIDO', 'Lido')], default='PENDENTE', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('tentativas_envio', models.IntegerField(default=0)),
                ('erro_envio', models.TextField(blank=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.camera')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.incidente')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.CharField(max_length=50, unique=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('PENDENTE', 'Pendente')], default='CONCLUIDA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.funcionario')),
            ],
            options={
                'verbose_name': 'Operação de Venda',
                'verbose_name_plural': 'Operações de Vendas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='incidente',
            name='operacao_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.operacaovenda'),
        ),
        migrations.CreateModel(
            name='PerfilGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acesso', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('receber_alertas_email', models.BooleanField(default=True)),
                ('receber_alertas_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Gestor',
                'verbose_name_plural': 'Perfis de Gestores',
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='verifik.operacaovenda')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.produto')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
            },
        ),
    ]
