# Generated by Django 5.2.7 on 2025-11-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0002_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/treino/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_treino', to='verifik.produto')),
            ],
            options={
                'verbose_name': 'Imagem de Produto',
                'verbose_name_plural': 'Imagens de Produtos',
                'ordering': ['produto', 'ordem', 'id'],
            },
        ),
    ]
