# Generated by Django 5.2.7 on 2025-11-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_can_access_erp_hub_and_more'),
        ('verifik', '0003_imagemproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifik_funcionarios', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='produto',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifik_produtos', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('organization', 'codigo_barras')},
        ),
    ]
