# Generated by Django 5.2.7 on 2025-11-20 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_can_access_erp_hub_and_more'),
        ('verifik', '0004_funcionario_organization_produto_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifik_cameras', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='operacaovenda',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifik_vendas', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='operacaovenda',
            name='numero_venda',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='operacaovenda',
            unique_together={('organization', 'numero_venda')},
        ),
    ]
