# Generated by Django 5.2.7 on 2025-11-20 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0005_camera_organization_operacaovenda_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço de referência', max_digits=10)),
                ('imagem_referencia', models.ImageField(blank=True, null=True, upload_to='produtos_mae/')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto Mãe',
                'verbose_name_plural': 'Produtos Mãe',
                'ordering': ['descricao_produto'],
            },
        ),
        migrations.AlterField(
            model_name='deteccaoproduto',
            name='produto_identificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.produtomae'),
        ),
        migrations.AlterField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_treino', to='verifik.produtomae'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifik.produtomae'),
        ),
        migrations.CreateModel(
            name='CodigoBarrasProdutoMae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código de barras único globalmente', max_length=50, unique=True)),
                ('principal', models.BooleanField(default=False, help_text='Código principal deste produto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_barras', to='verifik.produtomae')),
            ],
            options={
                'verbose_name': 'Código de Barras (Produto Mãe)',
                'verbose_name_plural': 'Códigos de Barras (Produto Mãe)',
                'ordering': ['-principal', 'codigo'],
                'indexes': [models.Index(fields=['codigo'], name='verifik_cod_codigo_c76c06_idx'), models.Index(fields=['produto_mae', 'principal'], name='verifik_cod_produto_9c14c1_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
