# Generated by Django 5.2.7 on 2025-11-25 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_organization_address_alter_organization_cnpj_and_more'),
        ('verifik', '0006_produtomae_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigobarrasprodutomae',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Código de barras (EAN-13, EAN-8, etc.)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='codigobarrasprodutomae',
            name='principal',
            field=models.BooleanField(default=False, help_text='Código principal do produto (mostrar primeiro)'),
        ),
        migrations.AlterField(
            model_name='codigobarrasprodutomae',
            name='produto_mae',
            field=models.ForeignKey(help_text='Produto ao qual este código pertence', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_barras', to='verifik.produtomae'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se False, funcionário foi desligado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(help_text='Cargo (ex: Operador de Caixa, Gerente)', max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='CPF do funcionário', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(help_text='Data de contratação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, help_text='Data de desligamento (se houver)', null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do funcionário (opcional)', null=True, upload_to='funcionarios/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(help_text='Número de matrícula único', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo do funcionário', max_length=255),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização à qual o funcionário pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifik_funcionarios', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuário do sistema (se tiver acesso ao painel)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilgestor',
            name='nivel_acesso',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente'), ('ADMINISTRADOR', 'Administrador')], help_text='Nível de permissões no sistema', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilgestor',
            name='receber_alertas_email',
            field=models.BooleanField(default=True, help_text='Enviar alertas por email'),
        ),
        migrations.AlterField(
            model_name='perfilgestor',
            name='receber_alertas_whatsapp',
            field=models.BooleanField(default=False, help_text='Enviar alertas por WhatsApp (futuro)'),
        ),
        migrations.AlterField(
            model_name='perfilgestor',
            name='telefone',
            field=models.CharField(help_text='Telefone para notificações', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilgestor',
            name='usuario',
            field=models.OneToOneField(help_text='User associado (1-para-1)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se False, produto descontinuado'),
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='descricao_produto',
            field=models.CharField(help_text='Nome/descrição do produto (ex: Coca-Cola 350ml)', max_length=255),
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='imagem_referencia',
            field=models.ImageField(blank=True, help_text='Imagem principal do produto (thumb)', null=True, upload_to='produtos_mae/'),
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca do produto (ex: Coca-Cola, Pepsi)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço de referência em reais (R$)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='tipo',
            field=models.CharField(blank=True, help_text='Categoria (ex: Refrigerante, Chocolate, Cerveja)', max_length=100, null=True),
        ),
    ]
