# Generated by Django 5.2.8 on 2025-11-26 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0007_alter_codigobarrasprodutomae_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Coleta Loja Centro - 26/11/2025', max_length=200, verbose_name='Nome do lote')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('total_imagens', models.IntegerField(default=0, verbose_name='Total de imagens')),
                ('imagens_aprovadas', models.IntegerField(default=0, verbose_name='Imagens aprovadas')),
                ('imagens_rejeitadas', models.IntegerField(default=0, verbose_name='Imagens rejeitadas')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Lote de Fotos',
                'verbose_name_plural': 'Lotes de Fotos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProdutoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Foto do produto', upload_to='produtos/pendentes/%Y/%m/%d/', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação')),
                ('observacoes', models.TextField(blank=True, help_text='Comentários sobre a foto', verbose_name='Observações')),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Razão pela qual a imagem foi rejeitada', verbose_name='Motivo da rejeição')),
                ('qualidade', models.IntegerField(blank=True, help_text='Avaliação da qualidade da imagem', null=True, verbose_name='Qualidade (1-5)')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('produto', models.ForeignKey(help_text='Produto ao qual a imagem pertence', on_delete=django.db.models.deletion.CASCADE, to='verifik.produtomae', verbose_name='Produto')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens', to='verifik.lotefotos', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Imagem Pendente',
                'verbose_name_plural': 'Imagens Pendentes',
                'ordering': ['-data_envio'],
            },
        ),
    ]
