# Generated by Django 5.2.8 on 2025-11-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0008_lotefotos_imagemprodutopendente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemAnotada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Foto contendo um ou mais produtos', upload_to='produtos/anotacoes/%Y/%m/%d/', verbose_name='Imagem Original')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('status', models.CharField(choices=[('anotando', 'Em Anotação'), ('concluida', 'Concluída'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='anotando', max_length=20, verbose_name='Status')),
                ('total_anotacoes', models.IntegerField(default=0, help_text='Quantos produtos foram anotados nesta imagem', verbose_name='Total de anotações')),
                ('observacoes', models.TextField(blank=True, help_text='Comentários sobre a imagem', verbose_name='Observações')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_anotadas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_anotadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Imagem Anotada',
                'verbose_name_plural': 'Imagens Anotadas',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='AnotacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox_x', models.FloatField(help_text='Posição X do centro do box (0-1)', verbose_name='X (centro)')),
                ('bbox_y', models.FloatField(help_text='Posição Y do centro do box (0-1)', verbose_name='Y (centro)')),
                ('bbox_width', models.FloatField(help_text='Largura do box (0-1)', verbose_name='Largura')),
                ('bbox_height', models.FloatField(help_text='Altura do box (0-1)', verbose_name='Altura')),
                ('confianca', models.FloatField(default=1.0, help_text='Confiança na anotação (0-1)', verbose_name='Confiança')),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre esta anotação específica', verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('produto', models.ForeignKey(help_text='Produto identificado nesta região', on_delete=django.db.models.deletion.CASCADE, to='verifik.produtomae', verbose_name='Produto')),
                ('imagem_anotada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='verifik.imagemanotada', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Anotação de Produto',
                'verbose_name_plural': 'Anotações de Produtos',
                'ordering': ['imagem_anotada', 'id'],
            },
        ),
    ]
