# Generated by Django 5.2.8 on 2025-11-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0009_imagemanotada_anotacaoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemprodutopendente',
            name='bbox_data',
            field=models.TextField(blank=True, help_text='Coordenadas do bbox em formato JSON', verbose_name='Dados do Bounding Box'),
        ),
    ]
