# Generated by Django 5.2.8 on 2025-11-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0010_imagemprodutopendente_bbox_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemprodutopendente',
            name='metodo_deteccao',
            field=models.CharField(blank=True, help_text='Como o produto foi detectado (YOLO, código de barras, OCR, etc)', max_length=50, verbose_name='Método de Detecção'),
        ),
    ]
