# Generated by Django 5.2.8 on 2025-11-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0011_imagemprodutopendente_metodo_deteccao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria (ex: Cerveja, Refrigerante)', max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, help_text='Descrição da categoria', max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se está ativo no sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recipiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do recipiente (ex: LATA, LONG NECK, PET 1L)', max_length=100, unique=True)),
                ('volume_ml', models.IntegerField(blank=True, help_text='Volume em mililitros (ex: 350, 473, 600, 1000, 2000)', null=True)),
                ('aliases', models.TextField(blank=True, help_text='Aliases separados por vírgula para OCR (ex: LT,CAN,LATINHA)', null=True)),
                ('descricao', models.CharField(blank=True, help_text='Descrição do recipiente', max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se está ativo no sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recipiente',
                'verbose_name_plural': 'Recipientes',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca do produto (texto livre - legado)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtomae',
            name='tipo',
            field=models.CharField(blank=True, help_text='Categoria (texto livre - legado)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produtomae',
            name='categoria_fk',
            field=models.ForeignKey(blank=True, help_text='Categoria do produto (Cerveja, Refrigerante, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='verifik.categoria'),
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da marca (ex: Heineken, Coca-Cola)', max_length=100, unique=True)),
                ('aliases', models.TextField(blank=True, help_text='Aliases separados por vírgula para OCR (ex: COCA,COLA,COCA-COLA)', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se está ativo no sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoria principal desta marca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas', to='verifik.categoria')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produtomae',
            name='marca_fk',
            field=models.ForeignKey(blank=True, help_text='Marca do produto (Heineken, Coca-Cola, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='verifik.marca'),
        ),
        migrations.AddField(
            model_name='produtomae',
            name='recipiente_fk',
            field=models.ForeignKey(blank=True, help_text='Recipiente/embalagem (Lata, Long Neck, PET, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='verifik.recipiente'),
        ),
    ]
