# Generated by Django 5.2.8 on 2025-11-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0012_categoria_recipiente_alter_produtomae_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomae',
            name='data_treinamento',
            field=models.DateTimeField(blank=True, help_text='Data/hora do último treinamento', null=True),
        ),
        migrations.AddField(
            model_name='produtomae',
            name='qtd_imagens_treino',
            field=models.IntegerField(default=0, help_text='Quantidade de imagens usadas no treino'),
        ),
        migrations.AddField(
            model_name='produtomae',
            name='total_acertos',
            field=models.IntegerField(default=0, help_text='Quantas vezes a detecção foi confirmada como correta'),
        ),
        migrations.AddField(
            model_name='produtomae',
            name='total_deteccoes',
            field=models.IntegerField(default=0, help_text='Quantas vezes a IA detectou este produto'),
        ),
        migrations.AddField(
            model_name='produtomae',
            name='total_erros',
            field=models.IntegerField(default=0, help_text='Quantas vezes a detecção foi corrigida (estava errada)'),
        ),
        migrations.AddField(
            model_name='produtomae',
            name='treinado',
            field=models.BooleanField(default=False, help_text='Se a IA já foi treinada para reconhecer este produto'),
        ),
    ]
