# Generated by Django 5.2.8 on 2025-11-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0013_produtomae_data_treinamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_processada', models.ImageField(upload_to='processadas_sem_fundo/')),
                ('tipo_processamento', models.CharField(default='fundo_removido', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('imagem_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_processadas', to='verifik.imagemproduto')),
            ],
            options={
                'verbose_name': 'Imagem Processada',
                'verbose_name_plural': 'Imagens Processadas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
