# Generated by Django 5.2.8 on 2025-11-30 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifik', '0014_imagemprocessada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_modelo', models.CharField(help_text='Ex: yolov8n_v1, yolov8n_v2', max_length=50, verbose_name='Versao do Modelo')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inicio')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusao')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('processando', 'Processando'), ('concluido', 'Concluido'), ('erro', 'Erro')], default='iniciado', max_length=20, verbose_name='Status')),
                ('total_imagens', models.IntegerField(default=0, verbose_name='Total de Imagens Usadas')),
                ('total_produtos', models.IntegerField(default=0, verbose_name='Total de Produtos')),
                ('epocas', models.IntegerField(default=50, verbose_name='Epocas de Treino')),
                ('acuracia', models.FloatField(blank=True, null=True, verbose_name='Acuracia Final')),
                ('perda', models.FloatField(blank=True, null=True, verbose_name='Perda Final')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parametros do Treino')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
            ],
            options={
                'verbose_name': 'Historico de Treino',
                'verbose_name_plural': 'Historicos de Treino',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='anotacaoproduto',
            options={'ordering': ['imagem_anotada', 'id'], 'verbose_name': 'Anotacao de Produto', 'verbose_name_plural': 'Anotacoes de Produtos'},
        ),
        migrations.AlterField(
            model_name='anotacaoproduto',
            name='bbox_x',
            field=models.FloatField(help_text='Posicao X do centro do box (0-1)', verbose_name='X (centro)'),
        ),
        migrations.AlterField(
            model_name='anotacaoproduto',
            name='bbox_y',
            field=models.FloatField(help_text='Posicao Y do centro do box (0-1)', verbose_name='Y (centro)'),
        ),
        migrations.AlterField(
            model_name='anotacaoproduto',
            name='confianca',
            field=models.FloatField(default=1.0, help_text='Confianca na anotacao (0-1)', verbose_name='Confianca'),
        ),
        migrations.AlterField(
            model_name='anotacaoproduto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criacao'),
        ),
        migrations.AlterField(
            model_name='anotacaoproduto',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Notas sobre esta anotacao especifica', verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='anotacaoproduto',
            name='produto',
            field=models.ForeignKey(help_text='Produto identificado nesta regiao', on_delete=django.db.models.deletion.CASCADE, to='verifik.produtomae', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='imagemanotada',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovacao'),
        ),
        migrations.AlterField(
            model_name='imagemanotada',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Comentarios sobre a imagem', verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='imagemanotada',
            name='status',
            field=models.CharField(choices=[('anotando', 'Em Anotacao'), ('concluida', 'Concluida'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='anotando', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='imagemanotada',
            name='total_anotacoes',
            field=models.IntegerField(default=0, help_text='Quantos produtos foram anotados nesta imagem', verbose_name='Total de anotacoes'),
        ),
        migrations.CreateModel(
            name='ImagemUnificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imagem', models.CharField(choices=[('original', 'Imagem Original de Treino'), ('processada', 'Processada (Fundo Removido)'), ('anotada', 'Anotada (Multiplos Produtos com BBox)'), ('augmentada', 'Augmentada (Transformacoes)')], help_text='Tipo: original, processada, anotada, augmentada, etc', max_length=50, verbose_name='Tipo de Imagem')),
                ('arquivo', models.ImageField(upload_to='imagens_unificadas/%Y/%m/%d/', verbose_name='Arquivo de Imagem')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descricao')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('width', models.IntegerField(default=0, verbose_name='Largura (px)')),
                ('height', models.IntegerField(default=0, verbose_name='Altura (px)')),
                ('tamanho_bytes', models.IntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('anotando', 'Em Anotacao'), ('concluida', 'Concluida'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='ativa', max_length=20, verbose_name='Status')),
                ('tipo_processamento', models.CharField(blank=True, default='', help_text='Ex: fundo_removido', max_length=50, null=True, verbose_name='Tipo de Processamento')),
                ('foi_augmentada', models.BooleanField(default=False, verbose_name='Foi Augmentada')),
                ('tipo_augmentacao', models.CharField(blank=True, default='', help_text='Ex: rotacao_45, flip_horizontal, zoom_1.2, brightness_0.8', max_length=255, verbose_name='Tipo de Augmentacao')),
                ('total_anotacoes', models.IntegerField(default=0, help_text='Quantos produtos foram anotados (0 se nao anotada)', verbose_name='Total de Anotacoes')),
                ('bbox_x', models.FloatField(default=0.0, verbose_name='BBox Centro X (0-1)')),
                ('bbox_y', models.FloatField(default=0.0, verbose_name='BBox Centro Y (0-1)')),
                ('bbox_width', models.FloatField(default=0.0, verbose_name='BBox Largura (0-1)')),
                ('bbox_height', models.FloatField(default=0.0, verbose_name='BBox Altura (0-1)')),
                ('confianca', models.FloatField(default=0.0, verbose_name='Confianca (0-1)')),
                ('num_treinos', models.IntegerField(default=0, help_text='Quantas vezes esta imagem foi usada em treino', verbose_name='Vezes Treinada')),
                ('ultimo_treino', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo Treino')),
                ('versao_modelo', models.CharField(blank=True, default='', help_text='Versao do modelo YOLO em que foi treinada', max_length=50, verbose_name='Versao do Modelo')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criacao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualizacao')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovacao')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_unificadas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_unificadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('imagem_original', models.ForeignKey(blank=True, help_text='Se processada/augmentada, referencia a imagem original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='verifik.imagemunificada', verbose_name='Imagem Original')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_unificadas', to='verifik.produtomae', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem Unificada',
                'verbose_name_plural': 'Imagens Unificadas',
                'ordering': ['produto', 'tipo_imagem', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagemTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foi_usada', models.BooleanField(default=True, verbose_name='Foi Usada no Treino')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adicao')),
                ('historico_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='verifik.historicotreino', verbose_name='Treino')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='verifik.imagemunificada', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Imagem em Treino',
                'verbose_name_plural': 'Imagens em Treino',
            },
        ),
        migrations.AddIndex(
            model_name='imagemunificada',
            index=models.Index(fields=['produto', 'tipo_imagem'], name='verifik_ima_produto_b87817_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemunificada',
            index=models.Index(fields=['status'], name='verifik_ima_status_e4dd37_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemunificada',
            index=models.Index(fields=['ativa'], name='verifik_ima_ativa_df2837_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemunificada',
            index=models.Index(fields=['num_treinos'], name='verifik_ima_num_tre_565690_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagemtreino',
            unique_together={('imagem', 'historico_treino')},
        ),
    ]
