# Generated by Django 5.2.8 on 2025-11-20 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_type', models.CharField(choices=[('webpostos', 'WebPostos'), ('linx', 'Linx Sistemas'), ('bling', 'Bling ERP'), ('tiny', 'Tiny ERP'), ('sap', 'SAP Business One'), ('totvs', 'TOTVS Protheus'), ('sankhya', 'Sankhya'), ('omie', 'Omie'), ('conta_azul', 'Conta Azul'), ('senior', 'Senior Sistemas'), ('ifood', 'iFood'), ('uber_eats', 'Uber Eats'), ('rappi', 'Rappi'), ('ze_delivery', 'Zé Delivery'), ('subway_portal', 'Portal Subway'), ('custom', 'ERP Customizado')], max_length=20, verbose_name='Tipo de ERP')),
                ('name', models.CharField(help_text='Ex: WebPostos - Posto Centro', max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('api_url', models.URLField(blank=True, verbose_name='URL da API')),
                ('api_key', models.TextField(blank=True, verbose_name='API Key')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Usuário')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Senha')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='Configuração Extra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sync_frequency', models.IntegerField(default=30, verbose_name='Frequência Sync (min)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('sync_status', models.CharField(blank=True, max_length=20, verbose_name='Status Sync')),
                ('sync_error', models.TextField(blank=True, verbose_name='Erro de Sync')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='Mapeamento de Campos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_integrations', to='accounts.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Integração ERP',
                'verbose_name_plural': 'Integrações ERP',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'erp_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('city', models.CharField(default='Recife', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(default='PE', max_length=2, verbose_name='Estado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Loja/Posto',
                'verbose_name_plural': 'Lojas/Postos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciou em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminou em')),
                ('status', models.CharField(choices=[('running', 'Executando'), ('success', 'Sucesso'), ('error', 'Erro'), ('partial', 'Parcial')], max_length=20, verbose_name='Status')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Registros Processados')),
                ('records_created', models.IntegerField(default=0, verbose_name='Registros Criados')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Registros Atualizados')),
                ('records_failed', models.IntegerField(default=0, verbose_name='Registros com Erro')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='erp_hub.erpintegration', verbose_name='Integração')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-started_at'],
            },
        ),
    ]
