# Generated by Django 5.2.8 on 2025-11-20 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_access_erp_hub_user_can_access_fuel_prices_and_more'),
        ('erp_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ inválido. Use formato: 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, verbose_name='Inscrição Municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, verbose_name='Inscrição Estadual')),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use formato: 00.000-000', regex='^\\d{2}\\.\\d{3}-\\d{3}$')], verbose_name='CEP')),
                ('tipo_logradouro', models.CharField(choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('praca', 'Praça'), ('rodovia', 'Rodovia'), ('estrada', 'Estrada'), ('travessa', 'Travessa')], default='avenida', max_length=20, verbose_name='Tipo Logradouro')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('proprietario', models.CharField(max_length=200, verbose_name='Proprietário')),
                ('gerente', models.CharField(blank=True, max_length=200, verbose_name='Gerente')),
                ('nome_declarante', models.CharField(blank=True, max_length=200, verbose_name='Nome do Declarante')),
                ('cpf_declarante', models.CharField(blank=True, max_length=14, verbose_name='CPF do Declarante')),
                ('regime_tributario', models.CharField(choices=[('simples', 'Simples Nacional'), ('real', 'Lucro Real'), ('presumido', 'Lucro Presumido'), ('mei', 'MEI')], default='real', max_length=20, verbose_name='Regime Tributário')),
                ('codigo_receita', models.CharField(blank=True, max_length=20, verbose_name='Código de Receita')),
                ('codigo_externo', models.CharField(blank=True, max_length=50, verbose_name='Código Externo')),
                ('logomarca', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logomarca')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='accounts.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='PostoCombustivel',
            fields=[
                ('empresa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_hub.empresa')),
                ('bandeira', models.CharField(choices=[('vibra', 'Vibra (BR/Petrobras)'), ('shell', 'Shell'), ('ipiranga', 'Ipiranga'), ('raizen', 'Raízen (Shell)'), ('ale', 'Ale'), ('branca', 'Bandeira Branca'), ('outro', 'Outro')], default='vibra', max_length=20, verbose_name='Bandeira')),
                ('codigo_anp', models.CharField(blank=True, max_length=50, verbose_name='Código ANP')),
                ('servicos', models.JSONField(default=list, help_text='Lista de serviços oferecidos no posto', verbose_name='Serviços Oferecidos')),
                ('tem_conveniencia', models.BooleanField(default=False, verbose_name='Tem Loja de Conveniência')),
                ('numero_bombas', models.IntegerField(default=0, verbose_name='Número de Bombas')),
                ('numero_tanques', models.IntegerField(default=0, verbose_name='Número de Tanques')),
                ('numero_pistas', models.IntegerField(default=1, verbose_name='Número de Pistas')),
                ('capacidade_gasolina_comum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capacidade Gasolina Comum (L)')),
                ('capacidade_gasolina_aditivada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capacidade Gasolina Aditivada (L)')),
                ('capacidade_diesel_s10', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capacidade Diesel S10 (L)')),
                ('capacidade_diesel_comum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capacidade Diesel Comum (L)')),
                ('capacidade_etanol', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Capacidade Etanol (L)')),
                ('horario_abertura', models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento')),
                ('funciona_24h', models.BooleanField(default=False, verbose_name='Funciona 24h')),
                ('usa_webpostos', models.BooleanField(default=False, verbose_name='Usa WebPostos')),
                ('codigo_webpostos', models.CharField(blank=True, max_length=50, verbose_name='Código WebPostos')),
            ],
            options={
                'verbose_name': 'Posto de Combustível',
                'verbose_name_plural': 'Postos de Combustível',
                'ordering': ['nome_fantasia'],
            },
            bases=('erp_hub.empresa',),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('empresa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_hub.empresa')),
                ('tipo', models.CharField(choices=[('fast_food', 'Fast Food'), ('restaurante', 'Restaurante'), ('lanchonete', 'Lanchonete'), ('cafeteria', 'Cafeteria'), ('franquia', 'Franquia')], default='fast_food', max_length=20, verbose_name='Tipo')),
                ('e_franquia', models.BooleanField(default=False, verbose_name='É Franquia')),
                ('nome_franquia', models.CharField(blank=True, max_length=100, verbose_name='Nome da Franquia')),
                ('codigo_franquia', models.CharField(blank=True, max_length=50, verbose_name='Código Franquia')),
                ('numero_mesas', models.IntegerField(default=0, verbose_name='Número de Mesas')),
                ('capacidade_pessoas', models.IntegerField(default=0, verbose_name='Capacidade (pessoas)')),
                ('aceita_delivery', models.BooleanField(default=True, verbose_name='Aceita Delivery')),
                ('tem_ifood', models.BooleanField(default=False, verbose_name='Tem iFood')),
                ('tem_uber_eats', models.BooleanField(default=False, verbose_name='Tem Uber Eats')),
                ('tem_rappi', models.BooleanField(default=False, verbose_name='Tem Rappi')),
                ('horario_abertura', models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['nome_fantasia'],
            },
            bases=('erp_hub.empresa',),
        ),
        migrations.CreateModel(
            name='SistemaEnergiaSolar',
            fields=[
                ('empresa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_hub.empresa')),
                ('potencia_instalada_kwp', models.DecimalField(decimal_places=2, default=0, help_text='Potência total instalada em kilowatt-pico', max_digits=10, verbose_name='Potência Instalada (kWp)')),
                ('numero_paineis', models.IntegerField(default=0, verbose_name='Número de Painéis')),
                ('marca_paineis', models.CharField(blank=True, max_length=100, verbose_name='Marca dos Painéis')),
                ('marca_inversor', models.CharField(blank=True, max_length=100, verbose_name='Marca do Inversor')),
                ('geracao_media_mensal_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Geração Média Mensal (kWh)')),
                ('economia_media_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Economia Média Mensal (R$)')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('data_ativacao', models.DateField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('tem_sistema_monitoramento', models.BooleanField(default=False, verbose_name='Tem Sistema de Monitoramento')),
                ('url_monitoramento', models.URLField(blank=True, verbose_name='URL do Sistema de Monitoramento')),
                ('api_monitoramento', models.CharField(blank=True, max_length=200, verbose_name='API de Monitoramento')),
            ],
            options={
                'verbose_name': 'Sistema de Energia Solar',
                'verbose_name_plural': 'Sistemas de Energia Solar',
                'ordering': ['nome_fantasia'],
            },
            bases=('erp_hub.empresa',),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cnpj'], name='erp_hub_emp_cnpj_07b198_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['organization', 'ativa'], name='erp_hub_emp_organiz_75cb2d_idx'),
        ),
    ]
