# Generated by Django 5.2.8 on 2025-11-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_hub', '0002_empresa_postocombustivel_restaurante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroLubrificacao',
            fields=[
                ('empresa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_hub.empresa')),
                ('numero_boxes', models.IntegerField(default=1, verbose_name='Número de Boxes')),
                ('tem_elevador', models.BooleanField(default=False, verbose_name='Tem Elevador')),
                ('tem_rampa', models.BooleanField(default=False, verbose_name='Tem Rampa')),
                ('faz_troca_oleo', models.BooleanField(default=True, verbose_name='Faz Troca de Óleo')),
                ('faz_troca_filtros', models.BooleanField(default=True, verbose_name='Faz Troca de Filtros')),
                ('faz_alinhamento', models.BooleanField(default=False, verbose_name='Faz Alinhamento')),
                ('faz_balanceamento', models.BooleanField(default=False, verbose_name='Faz Balanceamento')),
                ('faz_lavagem_motor', models.BooleanField(default=False, verbose_name='Faz Lavagem de Motor')),
                ('atende_passeio', models.BooleanField(default=True, verbose_name='Atende Veículos de Passeio')),
                ('atende_moto', models.BooleanField(default=False, verbose_name='Atende Motos')),
                ('atende_caminhao', models.BooleanField(default=False, verbose_name='Atende Caminhões')),
                ('atende_onibus', models.BooleanField(default=False, verbose_name='Atende Ônibus')),
                ('marcas_lubrificantes', models.JSONField(default=list, help_text='Lista de marcas de lubrificantes comercializadas', verbose_name='Marcas de Lubrificantes')),
                ('horario_abertura', models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento')),
                ('atendimentos_dia', models.IntegerField(default=0, verbose_name='Atendimentos por Dia (média)')),
                ('tempo_medio_atendimento', models.IntegerField(default=30, verbose_name='Tempo Médio de Atendimento (min)')),
                ('posto', models.ForeignKey(blank=True, help_text='Posto onde o centro está localizado (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_lubrificacao', to='erp_hub.postocombustivel', verbose_name='Posto')),
            ],
            options={
                'verbose_name': 'Centro de Lubrificação',
                'verbose_name_plural': 'Centros de Lubrificação',
                'ordering': ['nome_fantasia'],
            },
            bases=('erp_hub.empresa',),
        ),
        migrations.CreateModel(
            name='LojaConveniencia',
            fields=[
                ('empresa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_hub.empresa')),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Área (m²)')),
                ('numero_checkouts', models.IntegerField(default=1, verbose_name='Número de Checkouts')),
                ('tem_padaria', models.BooleanField(default=False, verbose_name='Tem Padaria')),
                ('tem_cafe', models.BooleanField(default=False, verbose_name='Tem Café')),
                ('tem_freezer', models.BooleanField(default=True, verbose_name='Tem Área de Freezer')),
                ('aceita_vale_refeicao', models.BooleanField(default=False, verbose_name='Aceita Vale Refeição')),
                ('aceita_cartao_combustivel', models.BooleanField(default=False, verbose_name='Aceita Cartão de Combustível')),
                ('vende_bebidas', models.BooleanField(default=True, verbose_name='Vende Bebidas')),
                ('vende_alimentos', models.BooleanField(default=True, verbose_name='Vende Alimentos')),
                ('vende_higiene', models.BooleanField(default=True, verbose_name='Vende Higiene')),
                ('vende_automotivos', models.BooleanField(default=True, verbose_name='Vende Produtos Automotivos')),
                ('horario_abertura', models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento')),
                ('funciona_24h', models.BooleanField(default=False, verbose_name='Funciona 24h')),
                ('usa_sistema_pdv', models.BooleanField(default=False, verbose_name='Usa Sistema PDV')),
                ('nome_sistema_pdv', models.CharField(blank=True, max_length=100, verbose_name='Nome do Sistema PDV')),
                ('posto', models.ForeignKey(blank=True, help_text='Posto onde a conveniência está localizada (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lojas_conveniencia', to='erp_hub.postocombustivel', verbose_name='Posto')),
            ],
            options={
                'verbose_name': 'Loja de Conveniência',
                'verbose_name_plural': 'Lojas de Conveniência',
                'ordering': ['nome_fantasia'],
            },
            bases=('erp_hub.empresa',),
        ),
    ]
