# Generated by Django 5.2.8 on 2025-11-20 13:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('gas_station', 'Posto de Combustível'), ('convenience', 'Loja de Conveniência'), ('restaurant', 'Restaurante'), ('franchise', 'Franquia'), ('delivery', 'Delivery'), ('solar', 'Energia Solar'), ('retail', 'Varejo'), ('holding', 'Holding'), ('other', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuito (Trial)'), ('basic', 'Básico'), ('professional', 'Profissional'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Plano')),
                ('subscription_status', models.CharField(choices=[('active', 'Ativo'), ('trial', 'Trial'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='trial', max_length=20, verbose_name='Status')),
                ('subscription_started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciou em')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('max_stores', models.IntegerField(default=1, verbose_name='Máx. Lojas')),
                ('max_users', models.IntegerField(default=5, verbose_name='Máx. Usuários')),
                ('max_cameras', models.IntegerField(default=4, verbose_name='Máx. Câmeras')),
                ('max_erp_integrations', models.IntegerField(default=2, verbose_name='Máx. ERPs')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#D4AF37', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#1B4D3E', max_length=7, verbose_name='Cor Secundária')),
                ('custom_domain', models.CharField(blank=True, max_length=100, verbose_name='Domínio Customizado')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mensalidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar')),
                ('is_org_admin', models.BooleanField(default=False, verbose_name='Admin da Organização')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Super Admin LOGOS')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
