# Generated by Django 5.2.8 on 2025-11-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_erp_hub',
            field=models.BooleanField(default=False, help_text='Pode acessar integrações ERP', verbose_name='Acesso ERP Hub'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_fuel_prices',
            field=models.BooleanField(default=False, help_text='Pode acessar preços de combustível', verbose_name='Acesso Fuel Prices'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_verifik',
            field=models.BooleanField(default=False, help_text='Pode acessar módulo de câmeras', verbose_name='Acesso VerifiK'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_settings',
            field=models.BooleanField(default=False, help_text='Pode alterar configurações', verbose_name='Editar Configurações'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Pode aprovar/rejeitar usuários', verbose_name='Gerenciar Usuários'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Pode visualizar relatórios', verbose_name='Ver Relatórios'),
        ),
    ]
