# Generated by Django 5.2.7 on 2025-11-20 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_access_erp_hub_user_can_access_fuel_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_access_erp_hub',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_fuel_prices',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_verifik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_org_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='active_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='accounts.organization', verbose_name='Organização Ativa'),
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_org_admin', models.BooleanField(default=False, verbose_name='Admin da Organização')),
                ('can_access_verifik', models.BooleanField(default=False, verbose_name='Acesso VerifiK')),
                ('can_access_erp_hub', models.BooleanField(default=False, verbose_name='Acesso ERP Hub')),
                ('can_access_fuel_prices', models.BooleanField(default=False, verbose_name='Acesso Fuel Prices')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Gerenciar Usuários')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Ver Relatórios')),
                ('can_edit_settings', models.BooleanField(default=False, verbose_name='Editar Configurações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso à Organização',
                'verbose_name_plural': 'Acessos às Organizações',
                'ordering': ['organization__name'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
