# Generated by Django 5.2.7 on 2025-11-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_can_access_erp_hub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço completo', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da empresa (único no sistema)', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Domínio próprio (ex: posto.grupolisboa.com.br)', max_length=100, verbose_name='Domínio Customizado'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(help_text='Email de contato da organização', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se False, organização está desativada', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da empresa (aparece no sistema)', null=True, upload_to='organizations/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_cameras',
            field=models.IntegerField(default=4, help_text='Máximo de câmeras ativas', verbose_name='Máx. Câmeras'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_erp_integrations',
            field=models.IntegerField(default=2, help_text='Máximo de integrações com ERPs', verbose_name='Máx. ERPs'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_stores',
            field=models.IntegerField(default=1, help_text='Máximo de lojas/filiais permitidas', verbose_name='Máx. Lojas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.IntegerField(default=5, help_text='Máximo de usuários simultâneos', verbose_name='Máx. Usuários'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor mensal em reais (R$)', max_digits=10, verbose_name='Mensalidade'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Nome da organização (ex: Posto Lisboa Centro)', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone comercial', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#D4AF37', help_text='Cor principal da interface (hex)', max_length=7, verbose_name='Cor Primária'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#1B4D3E', help_text='Cor secundária da interface (hex)', max_length=7, verbose_name='Cor Secundária'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='URL amigável (gerado automaticamente do nome)', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='Data de expiração (trial ou suspensão)', null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Gratuito (Trial)'), ('basic', 'Básico'), ('professional', 'Profissional'), ('enterprise', 'Enterprise')], default='free', help_text='Plano de assinatura contratado', max_length=20, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de início da assinatura', verbose_name='Iniciou em'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Ativo'), ('trial', 'Trial'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='trial', help_text='Status atual da assinatura', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('gas_station', 'Posto de Combustível'), ('convenience', 'Loja de Conveniência'), ('restaurant', 'Restaurante'), ('franchise', 'Franquia'), ('delivery', 'Delivery'), ('solar', 'Energia Solar'), ('retail', 'Varejo'), ('holding', 'Holding'), ('other', 'Outro')], help_text='Tipo de negócio', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação', verbose_name='Atualizado em'),
        ),
    ]
