# Generated by Django 5.2.8 on 2025-11-20 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('erp_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('version', models.CharField(max_length=50, verbose_name='Versão')),
                ('model_file', models.CharField(help_text='Ex: yolov8n.pt', max_length=200, verbose_name='Arquivo Modelo')),
                ('model_type', models.CharField(choices=[('detection', 'Detecção de Objetos'), ('segmentation', 'Segmentação'), ('classification', 'Classificação'), ('pose', 'Detecção de Pose')], max_length=20, verbose_name='Tipo')),
                ('classes', models.JSONField(default=list, verbose_name='Classes')),
                ('avg_inference_time', models.FloatField(default=0, verbose_name='Tempo Inferência (ms)')),
                ('accuracy', models.FloatField(default=0, verbose_name='Acurácia %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(blank=True, help_text='Deixe vazio para modelo global', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Modelo IA',
                'verbose_name_plural': 'Modelos IA',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('location', models.CharField(help_text='Ex: Caixa 1, Pista 3, Estoque', max_length=200, verbose_name='Localização')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('stream_url', models.CharField(help_text='rtsp://usuario:senha@ip:porta/stream', max_length=500, verbose_name='URL Stream')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('port', models.IntegerField(default=554, verbose_name='Porta')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Usuário')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Senha')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Erro'), ('maintenance', 'Manutenção')], default='offline', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_recording', models.BooleanField(default=False, verbose_name='Gravando')),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='IA Habilitada')),
                ('ai_model', models.CharField(default='yolov8n.pt', max_length=50, verbose_name='Modelo IA')),
                ('confidence_threshold', models.FloatField(default=0.5, help_text='0.0 a 1.0', verbose_name='Threshold Confiança')),
                ('detection_fps', models.IntegerField(default=5, help_text='Frames por segundo para análise', verbose_name='FPS Detecção')),
                ('detection_classes', models.JSONField(default=list, help_text='["person", "car", "truck", "fire", "smoke"]', verbose_name='Classes para Detectar')),
                ('roi_polygon', models.JSONField(blank=True, help_text='Coordenadas do polígono: [[x1,y1], [x2,y2], ...]', null=True, verbose_name='Polígono ROI')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='Caminho Gravação')),
                ('retention_days', models.IntegerField(default=30, verbose_name='Dias Retenção')),
                ('last_frame_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Frame')),
                ('total_events', models.IntegerField(default=0, verbose_name='Total de Eventos')),
                ('uptime_percentage', models.FloatField(default=0.0, verbose_name='Uptime %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organização')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='erp_hub.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
                'ordering': ['store', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CameraSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Hora Início')),
                ('end_time', models.TimeField(verbose_name='Hora Fim')),
                ('enable_recording', models.BooleanField(default=True, verbose_name='Habilitar Gravação')),
                ('enable_detection', models.BooleanField(default=True, verbose_name='Habilitar Detecção IA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cameras.camera', verbose_name='Câmera')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('intrusion', 'Invasão Detectada'), ('loitering', 'Pessoa Parada Suspeita'), ('crowd', 'Aglomeração'), ('queue', 'Fila Detectada'), ('spillage', 'Derramamento de Produto'), ('fire', 'Fumaça/Fogo Detectado'), ('wrong_way', 'Veículo Contramão'), ('parking_violation', 'Estacionamento Irregular'), ('abandoned_vehicle', 'Veículo Abandonado'), ('shelf_empty', 'Prateleira Vazia'), ('theft', 'Possível Furto'), ('custom', 'Evento Customizado')], max_length=50, verbose_name='Tipo de Evento')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Severidade')),
                ('confidence', models.FloatField(help_text='Confiança da IA (0.0 a 1.0)', verbose_name='Confiança')),
                ('detected_objects', models.JSONField(help_text='Lista de objetos detectados com bounding boxes', verbose_name='Objetos Detectados')),
                ('snapshot_path', models.CharField(max_length=500, verbose_name='Caminho Snapshot')),
                ('video_clip_path', models.CharField(blank=True, max_length=500, verbose_name='Caminho Vídeo')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Reconhecido')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('action_taken', models.TextField(blank=True, verbose_name='Ação Tomada')),
                ('false_positive', models.BooleanField(default=False, verbose_name='Falso Positivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_events', to=settings.AUTH_USER_MODEL, verbose_name='Reconhecido por')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera', verbose_name='Câmera')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp'), ('system', 'Sistema')], max_length=20, verbose_name='Canal')),
                ('sent', models.BooleanField(default=False, verbose_name='Enviado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('read', models.BooleanField(default=False, verbose_name='Lido')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cameras.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['organization', 'is_active'], name='cameras_cam_organiz_b57f81_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['store', 'status'], name='cameras_cam_store_i_37fca2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['camera', '-detected_at'], name='cameras_eve_camera__3d8bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'severity'], name='cameras_eve_event_t_73d5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['acknowledged', '-detected_at'], name='cameras_eve_acknowl_61efb9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', '-created_at'], name='cameras_ale_user_id_afe0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['sent', 'read'], name='cameras_ale_sent_24a803_idx'),
        ),
    ]
