# Generated by Django 5.2.8 on 2025-11-26 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('padrao_ocr', models.TextField(blank=True, help_text='Padrão regex ou palavras-chave para identificação automática')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField(verbose_name='Data do Fechamento')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_processamento', 'Em Processamento'), ('aguardando_revisao', 'Aguardando Revisão'), ('revisado', 'Revisado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Vendas')),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Despesas')),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Líquido')),
                ('total_documentos', models.IntegerField(default=0, verbose_name='Total de Documentos')),
                ('documentos_processados', models.IntegerField(default=0, verbose_name='Documentos Processados')),
                ('documentos_revisados', models.IntegerField(default=0, verbose_name='Documentos Revisados')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='transcricao_caixa.empresa', verbose_name='Empresa')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Fechamento de Caixa',
                'verbose_name_plural': 'Fechamentos de Caixa',
                'ordering': ['-data_fechamento', '-criado_em'],
                'unique_together': {('empresa', 'data_fechamento')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoTranscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('entrada', 'Entrada (Venda)'), ('saida', 'Saída (Despesa)')], default='entrada', max_length=10, verbose_name='Tipo de Movimento')),
                ('imagem', models.ImageField(upload_to='transcricao_caixa/documentos/%Y/%m/%d/', verbose_name='Imagem do Documento')),
                ('imagem_processada', models.ImageField(blank=True, null=True, upload_to='transcricao_caixa/processadas/%Y/%m/%d/', verbose_name='Imagem Processada')),
                ('texto_completo', models.TextField(blank=True, verbose_name='Texto Completo (OCR)')),
                ('numero_documento', models.CharField(blank=True, max_length=100, verbose_name='Número do Documento')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('dados_extraidos', models.JSONField(blank=True, default=dict, help_text='Campos específicos extraídos do documento', verbose_name='Dados Extraídos')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro'), ('revisado', 'Revisado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('confianca_ocr', models.FloatField(default=0, help_text='Percentual de confiança na transcrição', verbose_name='Confiança do OCR (%)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('correcoes_manuais', models.TextField(blank=True, verbose_name='Correções Manuais')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('revisado_em', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_transcritos', to='transcricao_caixa.fechamentocaixa', verbose_name='Fechamento')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcricao_caixa.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento Transcrito',
                'verbose_name_plural': 'Documentos Transcritos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='Código')),
                ('unidade', models.CharField(blank=True, max_length=10, verbose_name='Unidade')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='transcricao_caixa.documentotranscrito', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Item do Documento',
                'verbose_name_plural': 'Itens do Documento',
                'ordering': ['documento', 'ordem'],
            },
        ),
    ]
