# Generated by Django 5.2.8 on 2025-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessadorImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('remover_fundo', 'Remover Fundo'), ('redimensionar', 'Redimensionar'), ('normalizar', 'Normalizar Cores'), ('aumentar_contraste', 'Aumentar Contraste')], max_length=20)),
                ('imagem_original', models.CharField(help_text='Caminho da imagem original', max_length=500)),
                ('imagem_processada', models.CharField(help_text='Caminho da imagem processada', max_length=500)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('processando', 'Processando')], default='sucesso', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(default=dict, help_text='Parâmetros usados no processamento')),
            ],
            options={
                'verbose_name': 'Processador de Imagens',
                'verbose_name_plural': 'Processadores de Imagens',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
