# Generated by Django 5.2.7 on 2025-11-21 22:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_organization_address_alter_organization_cnpj_and_more'),
        ('erp_hub', '0003_centrolubrificacao_lojaconveniencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do combustível (ex: Gasolina Comum)', max_length=100, unique=True, verbose_name='Nome')),
                ('code', models.CharField(help_text='Código interno (ex: GC, DS10, ET)', max_length=10, unique=True, verbose_name='Código Interno')),
                ('anp_code', models.CharField(blank=True, help_text='Código oficial da ANP (ex: 320101 para Gasolina C)', max_length=20, verbose_name='Código ANP')),
                ('fuel_type', models.CharField(choices=[('gasoline_common', 'Gasolina Comum'), ('gasoline_premium', 'Gasolina Aditivada'), ('ethanol', 'Etanol (Álcool)'), ('diesel_s10', 'Diesel S10'), ('diesel_s500', 'Diesel S500'), ('gnv', 'GNV (Gás Natural Veicular)')], help_text='Categoria do combustível', max_length=30, verbose_name='Tipo')),
                ('unit', models.CharField(default='litro', help_text='Unidade de medida (litro, m³, kg)', max_length=10, verbose_name='Unidade')),
                ('density', models.DecimalField(blank=True, decimal_places=3, help_text='Densidade aproximada (ex: 0.750 para gasolina)', max_digits=5, null=True, verbose_name='Densidade (kg/L)')),
                ('description', models.TextField(blank=True, help_text='Informações técnicas e características', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Se está disponível para comercialização', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome oficial da empresa', max_length=200, verbose_name='Razão Social')),
                ('brand', models.CharField(help_text='Nome comercial (ex: Vibra, Shell, Ipiranga)', max_length=100, verbose_name='Marca/Bandeira')),
                ('cnpj', models.CharField(help_text='CNPJ da distribuidora', max_length=18, unique=True, verbose_name='CNPJ')),
                ('contact_name', models.CharField(blank=True, help_text='Representante comercial', max_length=200, verbose_name='Nome do Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('portal_url', models.URLField(blank=True, help_text='URL do sistema web da distribuidora', verbose_name='URL do Portal')),
                ('has_web_scraping', models.BooleanField(default=False, help_text='Se temos scraper configurado para este fornecedor', verbose_name='Possui Scraping')),
                ('notes', models.TextField(blank=True, help_text='Condições especiais, histórico de negociações', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=3, help_text='Preço por litro SEM frete (ex: R$ 4,500)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Preço Unitário (Base)')),
                ('volume_liters', models.DecimalField(decimal_places=2, help_text='Quantidade de litros comprada (ex: 10000.00)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Volume (Litros)')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Valor total da nota fiscal (unit_price * volume + frete)', max_digits=12, verbose_name='Valor Total da NF')),
                ('freight_mode', models.CharField(choices=[('CIF', 'CIF (Vendedor paga frete)'), ('FOB', 'FOB (Comprador paga frete)')], default='CIF', help_text='CIF = Vendedor paga | FOB = Comprador paga', max_length=3, verbose_name='Modalidade de Frete')),
                ('freight_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo do frete em reais (R$ 0,00 se CIF)', max_digits=10, verbose_name='Valor do Frete')),
                ('freight_per_liter', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Calculado: freight_value / volume_liters', max_digits=6, verbose_name='Frete por Litro')),
                ('final_unit_cost', models.DecimalField(decimal_places=3, help_text='unit_price + freight_per_liter (CUSTO REAL)', max_digits=10, verbose_name='Custo Final por Litro')),
                ('payment_term_type', models.CharField(choices=[('antecipado', 'Antecipado (À Vista)'), ('prazo', 'A Prazo')], default='prazo', help_text='Antecipado (à vista) ou A Prazo', max_length=20, verbose_name='Tipo de Prazo')),
                ('payment_term_days', models.IntegerField(default=30, help_text='0 = à vista | 7, 15, 30, 60, 90 dias', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Prazo (Dias)')),
                ('early_payment_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% de desconto se pagar à vista (ex: 2.00 = 2%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Desconto Antecipado (%)')),
                ('payment_due_date', models.DateField(help_text='invoice_date + payment_term_days', verbose_name='Vencimento')),
                ('invoice_number', models.CharField(help_text='Número da nota fiscal', max_length=50, verbose_name='Número da NF')),
                ('invoice_date', models.DateField(help_text='Data de emissão da nota fiscal', verbose_name='Data da NF')),
                ('invoice_file', models.FileField(blank=True, help_text='Upload do PDF da nota fiscal (opcional)', null=True, upload_to='fuel_invoices/%Y/%m/', verbose_name='Arquivo da NF')),
                ('notes', models.TextField(blank=True, help_text='Negociações especiais, condições extras', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(help_text='Usuário que registrou esta compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_purchases_created', to=settings.AUTH_USER_MODEL)),
                ('fuel', models.ForeignKey(help_text='Tipo de combustível comprado', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='fuel_prices.fuel')),
                ('organization', models.ForeignKey(help_text='Organização que fez a compra', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_purchases', to='accounts.organization')),
                ('store', models.ForeignKey(help_text='Qual posto/loja comprou este combustível', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_purchases', to='erp_hub.store')),
                ('supplier', models.ForeignKey(help_text='Distribuidora que vendeu', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='fuel_prices.supplier')),
            ],
            options={
                'verbose_name': 'Compra de Combustível',
                'verbose_name_plural': 'Compras de Combustível',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=3, help_text='Preço por litro coletado do site', max_digits=10, verbose_name='Preço Unitário')),
                ('freight_mode', models.CharField(blank=True, choices=[('CIF', 'CIF (Vendedor paga frete)'), ('FOB', 'FOB (Comprador paga frete)')], help_text='CIF ou FOB (se o site informar)', max_length=3, null=True, verbose_name='Modalidade de Frete')),
                ('freight_included', models.BooleanField(default=True, help_text='Se o preço já inclui frete (CIF)', verbose_name='Frete Incluído')),
                ('payment_term_days', models.IntegerField(blank=True, help_text='Prazo de pagamento (se o site informar)', null=True, verbose_name='Prazo (Dias)')),
                ('source', models.CharField(choices=[('vibra_portal', 'Portal Vibra Energia'), ('anp', 'ANP (Dados Oficiais)'), ('manual', 'Entrada Manual'), ('ipiranga', 'Portal Ipiranga'), ('raizen', 'Portal Raízen')], help_text='De onde veio este preço', max_length=30, verbose_name='Fonte')),
                ('source_url', models.URLField(blank=True, help_text='Página onde foi coletado', verbose_name='URL de Origem')),
                ('scraped_at', models.DateTimeField(help_text='Data/hora da coleta', verbose_name='Coletado em')),
                ('raw_data', models.JSONField(blank=True, help_text='JSON completo coletado do site (para debug)', null=True, verbose_name='Dados Brutos')),
                ('is_valid', models.BooleanField(default=True, help_text='Se consideramos este preço confiável', verbose_name='Válido')),
                ('validation_notes', models.TextField(blank=True, help_text='Por que marcamos como inválido (se aplicável)', verbose_name='Notas de Validação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('fuel', models.ForeignKey(help_text='Tipo de combustível', on_delete=django.db.models.deletion.CASCADE, related_name='scraped_prices', to='fuel_prices.fuel')),
                ('store', models.ForeignKey(help_text='Para qual posto este preço foi coletado', on_delete=django.db.models.deletion.CASCADE, related_name='scraped_prices', to='erp_hub.store')),
                ('supplier', models.ForeignKey(help_text='Distribuidora que oferece este preço', on_delete=django.db.models.deletion.CASCADE, related_name='scraped_prices', to='fuel_prices.supplier')),
            ],
            options={
                'verbose_name': 'Preço Coletado (Scraping)',
                'verbose_name_plural': 'Preços Coletados (Scraping)',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('vibra_portal', 'Portal Vibra Energia'), ('anp', 'ANP (Dados Oficiais)'), ('manual', 'Entrada Manual'), ('ipiranga', 'Portal Ipiranga'), ('raizen', 'Portal Raízen')], help_text='Qual site foi acessado', max_length=30, verbose_name='Fonte')),
                ('started_at', models.DateTimeField(help_text='Quando começou a execução', verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Quando terminou (NULL se ainda rodando)', null=True, verbose_name='Finalizado em')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Tempo total de execução', null=True, verbose_name='Duração (s)')),
                ('status', models.CharField(choices=[('running', '🔄 Executando'), ('success', '✅ Sucesso'), ('partial', '⚠️ Parcial'), ('failed', '❌ Falhou')], default='running', max_length=20, verbose_name='Status')),
                ('prices_collected', models.IntegerField(default=0, help_text='Quantos preços foram salvos', verbose_name='Preços Coletados')),
                ('errors_count', models.IntegerField(default=0, help_text='Quantidade de erros encontrados', verbose_name='Erros')),
                ('error_message', models.TextField(blank=True, help_text='Descrição do erro (se houver)', verbose_name='Mensagem de Erro')),
                ('log_details', models.JSONField(blank=True, help_text='Informações técnicas da execução', null=True, verbose_name='Detalhes do Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('supplier', models.ForeignKey(blank=True, help_text='Fornecedor relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_logs', to='fuel_prices.supplier')),
            ],
            options={
                'verbose_name': 'Log de Scraping',
                'verbose_name_plural': 'Logs de Scraping',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('internal_divergence', '⚠️ Divergência Entre Postos'), ('better_price', '💡 Preço Melhor Disponível'), ('better_terms', '📅 Condições Melhores (Prazo/Frete)'), ('early_payment', '💰 Desconto Antecipado Disponível'), ('price_increase', '📈 Aumento de Preço Detectado'), ('price_decrease', '📉 Redução de Preço Detectada')], help_text='Categoria do alerta', max_length=30, verbose_name='Tipo de Alerta')),
                ('priority', models.CharField(choices=[('high', '🔴 Alta'), ('medium', '🟡 Média'), ('low', '🟢 Baixa')], default='medium', help_text='Alta/Média/Baixa', max_length=10, verbose_name='Prioridade')),
                ('current_price', models.DecimalField(decimal_places=3, help_text='Preço que você está pagando', max_digits=10, verbose_name='Preço Atual')),
                ('better_price', models.DecimalField(blank=True, decimal_places=3, help_text='Preço melhor disponível (se aplicável)', max_digits=10, null=True, verbose_name='Preço Melhor')),
                ('price_difference', models.DecimalField(decimal_places=3, help_text='Quanto você está pagando a mais', max_digits=8, verbose_name='Diferença (R$/L)')),
                ('potential_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Quanto economizaria (baseado em volume médio)', max_digits=12, null=True, verbose_name='Economia Potencial (R$)')),
                ('title', models.CharField(help_text='Título curto do alerta', max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Descrição completa do alerta', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, help_text='Se o gestor já visualizou', verbose_name='Lido')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Se foi descartado/ignorado', verbose_name='Dispensado')),
                ('dismissed_reason', models.TextField(blank=True, help_text='Por que foi ignorado', verbose_name='Motivo da Dispensa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Após esta data, alerta perde relevância', null=True, verbose_name='Expira em')),
                ('organization', models.ForeignKey(help_text='Organização que recebe o alerta', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_alerts', to='accounts.organization')),
                ('read_by', models.ForeignKey(blank=True, help_text='Usuário que leu o alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_alerts_read', to=settings.AUTH_USER_MODEL)),
                ('compared_purchase', models.ForeignKey(blank=True, help_text='Segunda compra para comparação (divergência interna)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_alerts', to='fuel_prices.purchaseprice')),
                ('purchase_price', models.ForeignKey(blank=True, help_text='Compra que gerou o alerta (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fuel_prices.purchaseprice')),
                ('scraped_price', models.ForeignKey(blank=True, help_text='Preço coletado que gerou o alerta (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fuel_prices.scrapedprice')),
            ],
            options={
                'verbose_name': 'Alerta de Preço',
                'verbose_name_plural': 'Alertas de Preço',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='fuel_prices_organiz_944a6b_idx'), models.Index(fields=['is_read', '-created_at'], name='fuel_prices_is_read_bbf90d_idx'), models.Index(fields=['priority', '-created_at'], name='fuel_prices_priorit_ef7ac3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='scrapedprice',
            index=models.Index(fields=['store', 'fuel', '-scraped_at'], name='fuel_prices_store_i_61c6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedprice',
            index=models.Index(fields=['supplier', '-scraped_at'], name='fuel_prices_supplie_85c489_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedprice',
            index=models.Index(fields=['-scraped_at'], name='fuel_prices_scraped_08051e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseprice',
            index=models.Index(fields=['store', 'fuel', '-invoice_date'], name='fuel_prices_store_i_f8ca81_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseprice',
            index=models.Index(fields=['supplier', '-invoice_date'], name='fuel_prices_supplie_b02fef_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseprice',
            index=models.Index(fields=['invoice_date'], name='fuel_prices_invoice_3a6a74_idx'),
        ),
    ]
