# Generated by Django 5.2.7 on 2025-11-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostoVibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vibra', models.CharField(max_length=20, unique=True, verbose_name='Código Vibra')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Posto Vibra',
                'verbose_name_plural': 'Postos Vibra',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='PrecoVibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('produto_codigo', models.CharField(max_length=50, verbose_name='Código do Produto')),
                ('preco', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Preço')),
                ('prazo_pagamento', models.CharField(blank=True, max_length=50, verbose_name='Prazo de Pagamento')),
                ('base_distribuicao', models.CharField(blank=True, max_length=100, verbose_name='Base de Distribuição')),
                ('modalidade', models.CharField(blank=True, max_length=50, verbose_name='Modalidade')),
                ('data_coleta', models.DateTimeField(verbose_name='Data da Coleta')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='fuel_prices.postovibra')),
            ],
            options={
                'verbose_name': 'Preço Vibra',
                'verbose_name_plural': 'Preços Vibra',
                'ordering': ['-data_coleta', 'produto_nome', 'posto'],
                'indexes': [models.Index(fields=['-data_coleta', 'produto_nome'], name='fuel_prices_data_co_aeb752_idx'), models.Index(fields=['posto', '-data_coleta'], name='fuel_prices_posto_i_bdfc12_idx')],
            },
        ),
    ]
