# Generated by Django 5.2.7 on 2025-11-25 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsinaSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Usina')),
                ('localizacao', models.CharField(max_length=300, verbose_name='Localização')),
                ('capacidade_kwp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidade Instalada (kWp)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('data_instalacao', models.DateField(verbose_name='Data de Instalação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Usina Ativa')),
                ('inversor_marca', models.CharField(blank=True, max_length=100)),
                ('inversor_modelo', models.CharField(blank=True, max_length=100)),
                ('api_endpoint', models.URLField(blank=True, help_text='URL da API do inversor')),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usina Solar',
                'verbose_name_plural': 'Usinas Solares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AlertaUsina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('aviso', 'Aviso'), ('alerta', 'Alerta'), ('critico', 'Crítico')], max_length=20)),
                ('categoria', models.CharField(choices=[('producao', 'Produção'), ('temperatura', 'Temperatura'), ('tensao', 'Tensão'), ('comunicacao', 'Comunicação'), ('eficiencia', 'Eficiência'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes_resolucao', models.TextField(blank=True)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='solar_monitor.usinasolar')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('energia_gerada_total_kwh', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Energia Total Gerada (kWh)')),
                ('energia_media_dia_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Média Diária (kWh)')),
                ('potencia_pico_kw', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potência Pico (kW)')),
                ('horas_sol_pico', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas de Sol Pico')),
                ('co2_evitado_total_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='CO₂ Total Evitado (kg)')),
                ('economia_total_reais', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Economia Total (R$)')),
                ('eficiencia_media_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eficiência Média (%)')),
                ('dias_offline', models.IntegerField(default=0, verbose_name='Dias Offline')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='solar_monitor.usinasolar')),
            ],
            options={
                'verbose_name': 'Relatório Mensal',
                'verbose_name_plural': 'Relatórios Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('usina', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='LeituraUsina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('potencia_atual_kw', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Potência Atual (kW)')),
                ('energia_gerada_kwh', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Energia Gerada Acumulada (kWh)')),
                ('energia_dia_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Energia do Dia (kWh)')),
                ('irradiancia_w_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Irradiância (W/m²)')),
                ('temperatura_modulo_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura do Módulo (°C)')),
                ('temperatura_ambiente_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente (°C)')),
                ('tensao_v', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tensão (V)')),
                ('corrente_a', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Corrente (A)')),
                ('frequencia_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frequência (Hz)')),
                ('eficiencia_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eficiência (%)')),
                ('fator_potencia', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Fator de Potência')),
                ('co2_evitado_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CO₂ Evitado (kg)')),
                ('economia_reais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Economia Estimada (R$)')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('manutencao', 'Manutenção'), ('alerta', 'Alerta'), ('erro', 'Erro')], default='online', max_length=20)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='solar_monitor.usinasolar')),
            ],
            options={
                'verbose_name': 'Leitura da Usina',
                'verbose_name_plural': 'Leituras das Usinas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usina', '-timestamp'], name='solar_monit_usina_i_2eab44_idx'), models.Index(fields=['timestamp'], name='solar_monit_timesta_2f54e5_idx')],
            },
        ),
    ]
