# Generated by Django 5.2.7 on 2025-11-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_monitor', '0002_modeloplacasolar_remove_usinasolar_api_endpoint_and_more'),
    ]

    operations = [
    ]
