# Generated by Django 5.2.7 on 2025-11-26 00:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_monitor', '0003_migrate_inversor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usinasolar',
            name='altitude_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altitude em metros acima do nível do mar', max_digits=6, null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='distancia_estacao_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distância da Estação (km)'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='estacao_meteo_codigo',
            field=models.CharField(blank=True, help_text='Código INMET da estação mais próxima', max_length=50, verbose_name='Código Estação Meteorológica'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='estacao_meteo_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome Estação Meteorológica'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='estado',
            field=models.CharField(blank=True, help_text='Ex: PE, SP, RJ', max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='irradiancia_media_anual_kwh_m2_dia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HSP médio anual da região (ex: Recife ≈ 5.2)', max_digits=5, null=True, verbose_name='Irradiância Média Anual (kWh/m²/dia)'),
        ),
        migrations.AddField(
            model_name='usinasolar',
            name='temperatura_media_anual_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura média da região', max_digits=4, null=True, verbose_name='Temperatura Média Anual (°C)'),
        ),
        migrations.AlterField(
            model_name='usinasolar',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada GPS - Latitude (ex: -8.047562)', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='usinasolar',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada GPS - Longitude (ex: -34.877001)', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='AnalisePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateField(verbose_name='Data da Análise')),
                ('energia_gerada_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Energia Gerada Real (kWh)')),
                ('energia_esperada_ideal_kwh', models.DecimalField(decimal_places=2, help_text='Geração esperada em céu limpo', max_digits=10, verbose_name='Energia Esperada - Condições Ideais (kWh)')),
                ('energia_esperada_real_kwh', models.DecimalField(decimal_places=2, help_text='Geração esperada considerando clima real', max_digits=10, verbose_name='Energia Esperada - Condições Reais (kWh)')),
                ('irradiancia_media_w_m2', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Irradiância Média (W/m²)')),
                ('hsp_dia_kwh_m2', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='HSP do Dia (kWh/m²)')),
                ('temperatura_media_c', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura Média (°C)')),
                ('nebulosidade_media_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nebulosidade Média (%)')),
                ('precipitacao_total_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Precipitação Total (mm)')),
                ('pr_ideal_percent', models.DecimalField(decimal_places=2, help_text='Performance Ratio comparado com condições ideais', max_digits=5, verbose_name='PR vs Ideal (%)')),
                ('pr_real_percent', models.DecimalField(decimal_places=2, help_text='Performance Ratio comparado com condições reais do dia', max_digits=5, verbose_name='PR vs Real (%)')),
                ('status_performance', models.CharField(choices=[('excelente', 'Excelente (≥95%)'), ('bom', 'Bom (85-95%)'), ('aceitavel', 'Aceitável (75-85%)'), ('abaixo', 'Abaixo do Esperado (60-75%)'), ('critico', 'Crítico (<60%)')], max_length=30, verbose_name='Status da Performance')),
                ('perda_temperatura_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Perda por Temperatura (%)')),
                ('perda_sujeira_estimada_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Perda por Sujeira Estimada (%)')),
                ('perda_sombreamento_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Perda por Sombreamento (%)')),
                ('justificativa_climatica', models.TextField(blank=True, help_text='Explicação automática sobre impacto do clima na geração', verbose_name='Justificativa Climática')),
                ('requer_atencao', models.BooleanField(default=False, verbose_name='Requer Atenção')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_performance', to='solar_monitor.usinasolar', verbose_name='Usina')),
            ],
            options={
                'verbose_name': 'Análise de Performance',
                'verbose_name_plural': 'Análises de Performance',
                'ordering': ['-data_analise'],
                'unique_together': {('usina', 'data_analise')},
            },
        ),
        migrations.CreateModel(
            name='DadosMeteorologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('irradiancia_global_w_m2', models.DecimalField(decimal_places=2, help_text='Radiação solar total na superfície', max_digits=7, verbose_name='Irradiância Global (W/m²)')),
                ('irradiancia_direta_w_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Irradiância Direta (W/m²)')),
                ('irradiancia_difusa_w_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Irradiância Difusa (W/m²)')),
                ('temperatura_ar_c', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura do Ar (°C)')),
                ('sensacao_termica_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sensação Térmica (°C)')),
                ('nebulosidade_percent', models.DecimalField(decimal_places=2, help_text='% de cobertura de nuvens (0=céu limpo, 100=totalmente nublado)', max_digits=5, verbose_name='Nebulosidade (%)')),
                ('condicao_clima', models.CharField(choices=[('ceu_limpo', 'Céu Limpo'), ('parcialmente_nublado', 'Parcialmente Nublado'), ('nublado', 'Nublado'), ('chuvoso', 'Chuvoso'), ('tempestade', 'Tempestade'), ('nevoa', 'Névoa/Neblina')], max_length=50, verbose_name='Condição Climática')),
                ('precipitacao_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantidade de chuva acumulada', max_digits=6, verbose_name='Precipitação (mm)')),
                ('chovendo', models.BooleanField(default=False, verbose_name='Está Chovendo')),
                ('velocidade_vento_km_h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidade do Vento (km/h)')),
                ('direcao_vento_graus', models.DecimalField(blank=True, decimal_places=2, help_text='0°=Norte, 90°=Leste, 180°=Sul, 270°=Oeste', max_digits=5, null=True, verbose_name='Direção do Vento (°)')),
                ('umidade_relativa_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Umidade Relativa (%)')),
                ('pressao_atmosferica_hpa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Pressão Atmosférica (hPa)')),
                ('visibilidade_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Visibilidade (km)')),
                ('indice_uv', models.DecimalField(blank=True, decimal_places=1, help_text='Índice de radiação ultravioleta (0-11+)', max_digits=4, null=True, verbose_name='Índice UV')),
                ('fonte_dados', models.CharField(choices=[('inmet', 'INMET - Instituto Nacional de Meteorologia'), ('openweather', 'OpenWeatherMap API'), ('weatherapi', 'WeatherAPI'), ('sensor_local', 'Sensor Local da Usina'), ('manual', 'Inserção Manual')], default='openweather', max_length=100, verbose_name='Fonte dos Dados')),
                ('hsp_dia_kwh_m2', models.DecimalField(blank=True, decimal_places=3, help_text='Horas de Sol Pico acumuladas no dia', max_digits=5, null=True, verbose_name='HSP do Dia (kWh/m²)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_meteorologicos', to='solar_monitor.usinasolar', verbose_name='Usina')),
            ],
            options={
                'verbose_name': 'Dados Meteorológicos',
                'verbose_name_plural': 'Dados Meteorológicos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usina', '-timestamp'], name='solar_monit_usina_i_be1e7e_idx'), models.Index(fields=['timestamp'], name='solar_monit_timesta_80d8bb_idx')],
                'unique_together': {('usina', 'timestamp')},
            },
        ),
    ]
